---

- name: devops test playbook 
  gather_facts: false
  hosts: all
  tasks:

    - name: Ping all servers and save the results in ping-output.txt
      shell:
        cmd: ping 127.0.0.1 >> /tmp/ping-output.txt

    - name: Ping all servers and save the results in ping-output.txt
      shell:
        cmd: ping 10.1.18.190 >> /tmp/ping-output.txt

    - name: Copy the httpd.conf file to /tmp and tag this task called push
      copy:
        src: /root/rae-test/httpd.conf
        dest: /tmp/httpd.conf
      tags:
        - push

    - name: Print stype value for each node
      debug:
        msg: stype value for {{ iventory_hostname }} is {{ stype }}

    - name: Tar the /tmp/ directory only when the variable stype=service
      archive:
        path: /tmp/
        dest: /opt/tmp.tar
      when: stype=="service"

